version: "2"
services:
  cli:
    build: .
    volumes:
      - .:/usr/src/app
    links:
      - db
    depends_on:
      - db
    networks:
      - default
    command: ["./wait-for-it.sh", "db:3306", "--", "php", "demo.php"]
  db:
    image: "mysql:5.7"
    environment:
      MYSQL_DATABASE: statcheck
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
    networks:
      - default